kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world-ws
  ports:
  - name: http
    protocol: TCP
    port: 8008
    targetPort: 9035
    nodePort: 30001
  type: NodePort