apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world-ws
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-ws
  template:
    metadata:
      labels:
        app: hello-world-ws
    spec:
      containers:
      - name: hello-world-ws
        image: hello-world-ws:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9035